{% set version="2.4" %}

package:
  name: besca
  version: {{ version }}

source:
  url: https://github.com/bedapub/besca/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2c889b2c139c55dce624a2712c4ff85da218f6831b70f800b707576a6cf1d9f0

build:
  number: 0
  noarch: python

requirements:
  host:
  - python >=3.8
  - pip
  run:
  - python >=3.8
  - scipy>=1.5.4
  - flask-restful
  - dominate
  - requests
  - numpy>=1.18.0
  - scanpy>=1.7.2
  - plotly
  - anndata>=0.7.4
  - seaborn
  - mygene
  - pandas>=1.1.0
  - matplotlib>=3.5.0
  - bbknn
  - ipython
  - nbclean
  - python-igraph
  - leidenalg>=0.8.3
  - scanorama
  - scvelo
  - umap-learn
  - sinfo
  - pydot
  - scvi-tools
  - ipython
  - scikit_learn>=1.0.0


about:
  home: https://github.com/bedapub/besca
  license: GNU GENERAL PUBLIC LICENSE Version 3
  license_family: GPL3
  license_file: LICENSE
  summary: "test"
